config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'home#index'

  get '/login', to: 'login#login', as: 'login'
  post '/login', to: 'login#do_login'
  delete '/logout', to: 'login#logout', as: 'logout'

  resources :roles
  resources :months
  resources :events
  resources :payments
  resources :notifications
  resources :users do
    delete '/:role_id', action: 'destroy_role', as: 'destroy_role'
    post '/new_role', action: 'new_role', as: 'new_role'
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  validates_presence_of :text, :elapseDate

  scope :visible, -> { where('"elapseDate" >= ?', Date.today) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :load_notification, only: [:show, :update, :edit, :destroy]

  def index
    authorize :notification, :index?

    @notifications = Notification.all
    respond_to do |f|
      f.html
      f.json { render json: @notifications }
    end
  end
  def show
    authorize @notification

    respond_to do |f|
      f.html
      f.json { render json: @notification }
    end
  end

  def update
    authorize @notification

    if @notification.update(notification_params)
      redirect_to @notification
    else
      render :edit
    end
  end
  def edit
    authorize @notification
  end

  def create
    @notification = Notification.new(notification_params)
    authorize @notification

    if @notification.save
      redirect_to @notification
    else
      render :new
    end
  end
  def new
    @notification = Notification.new
    authorize @notification
  end

  def destroy
    authorize @notification

    if @notification.destroy
      redirect_to root_path
    else
      redirect_to @notification
    end
  end

  private

  def load_notification
    @notification = Notification.find params[:id]
  end

  def notification_params
    params.require(:notification).permit(:text, :importance, :elapseDate)
  end
end

app/views/notifications/_form.html.erb
<%= form_for @notification, :html => { class: "form-horizontal notification" } do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @notification.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row"><div class="col-md-6">
    <div class="control-group">
      <%= f.label :text, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :text, class: 'form-control' %>
      </div>
      <%= error_span(@notification[:text]) %>
    </div>
    <div class="control-group">
      <%= f.label :importance, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :importance, class: 'form-control' %>
      </div>
      <%= error_span(@notification[:importance]) %>
    </div>
    <div class="control-group">
      <%= f.label :elapseDate, class: 'control-label' %>
      <div class="controls">
        <%= f.date_field :elapseDate, class: 'form-control' %>
      </div>
      <%= error_span(@notification[:elapseDate]) %>
    </div>
  </div></div>
  <div class="clearfix"></div>
  <br>

  <%= f.submit nil, class: 'btn btn-primary' %>
  <%= link_to t('cancel'), notifications_path, class: 'btn btn-default' %>

<% end %>

app/views/notifications/edit.html.erb
<div class="page-header">
  <h1><%=t 'notifications.edit_notification' %></h1>
</div>
<%= render 'form' %>

app/views/notifications/index.html.erb
<div class="page-header">
  <h1><%=t 'notifications.notifications' %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= Notification.human_attribute_name(:id) %></th>
    <th><%= Notification.human_attribute_name(:text) %></th>
    <th><%= Notification.human_attribute_name(:importance) %></th>
    <th><%= Notification.human_attribute_name(:elapseDate) %></th>
    <th><%=t 'actions' %></th>
  </tr>
  </thead>
  <tbody>
  <% @notifications.each do |notification| %>
    <tr>
      <td><%= link_to notification.id, notification_path(notification) %></td>
      <td><%= notification.text %></td>
      <td><%= notification.importance %></td>
      <td><%= format_date notification.elapseDate %></td>
      <td>
        <%= link_to t('edit'), edit_notification_path(notification), class: 'btn btn-default btn-xs' %>
        <%= link_to t('destroy'), notification_path(notification),
                    method: :delete,
                    data: { confirm: t('confirm') },
                    class: 'btn btn-xs btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('notifications.new_notification'), new_notification_path, class: 'btn btn-primary' %>

app/views/notifications/new.html.erb
<div class="page-header">
  <h1><%=t 'notifications.new_notification' %></h1>
</div>
<%= render 'form' %>

app/views/notifications/show.html.erb
<div class="page-header">
  <h1><%=t 'notifications.notification' %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= Notification.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @notification.text %></dd>
  <dt><strong><%= Notification.human_attribute_name(:importance) %>:</strong></dt>
  <dd><%= @notification.importance %></dd>
  <dt><strong><%= Notification.human_attribute_name(:elapseDate) %>:</strong></dt>
  <dd><%= format_date @notification.elapseDate %></dd>
</dl>

<br>
<%= link_to t('back'), notifications_path, class: 'btn btn-default'  %>
<%= link_to t('edit'), edit_notification_path(@notification), class: 'btn btn-default' %>
<%= link_to t('destroy'), notification_path(@notification),
            method: 'delete',
            data: { confirm: t('confirm') },
            class: 'btn btn-danger' %>