config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'home#index'

  get '/login', to: 'login#login', as: 'login'
  post '/login', to: 'login#do_login'
  delete '/logout', to: 'login#logout', as: 'logout'

  resources :roles
  resources :months
  resources :events
  resources :payments
  resources :notifications
  resources :users do
    delete '/:role_id', action: 'destroy_role', as: 'destroy_role'
    post '/new_role', action: 'new_role', as: 'new_role'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :username

  default_scope ->{ order('deleted ASC, banned ASC, name') }

  has_many :roles, through: :users_role
  has_many :users_role
  has_many :payments

  def additional_badges
    return @additional_badges if @additional_badges
    @additional_badges = []
    add_gentleman_badge
    add_rotten_badge
    @additional_badges
  end

  def missing_months(target_month = Date.today.beginning_of_month)
    past = payments.joins(:month).where('"firstDay" <= ?', Date.today.beginning_of_month).order('"firstDay"')
    return [] if past.size == 0
    ids = Month.where('"firstDay" >= ?', past.first.month.firstDay).where('"firstDay" <= ?', target_month).pluck(:id) - past.pluck(:month_id)
    Month.find(ids)
  end

  protected
  def add_gentleman_badge
    has_gentleman_payment = payments.joins(:month).where('"firstDay" > ?', Date.today.end_of_month).count
    @additional_badges.push([I18n.t('badges.gentleman'), 'badge-pro']) if has_gentleman_payment > 0
  end

  def add_rotten_badge
    if !deleted && !banned && missing_months.size != 0
      @additional_badges.push([I18n.t('badges.rotten'), 'label-danger'])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :update, :edit, :destroy, :new_role, :destroy_role]

  def index
    authorize :user, :index?

    @users = User.all
    respond_to do |f|
      f.html
      f.json { render json: @users }
    end
  end
  def show
    authorize @user

    @roles = @user.roles

    respond_to do |f|
      f.html
      f.json { render json: @user }
    end
  end

  def update
    authorize @user

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end
  def edit
  end

  def create
    @user = User.new(user_params)
    authorize @user

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end
  def new
    @user = User.new
    authorize @user
  end
  def new_role
    authorize @user

    role_id = params[:user].try(:[], :role_id)

    UsersRole.create user: @user, role: Role.find(role_id)
    redirect_to @user
  end

  def destroy
    authorize @user

    if @user.destroy
      redirect_to root_path
    else
      redirect_to @user
    end
  end
  def destroy_role
    authorize @user

    UsersRole.destroy_all(user_id: @user, role_id: params[:role_id])
    redirect_to @user
  end

  private

  def load_user
    @user = User.find(params[:user_id] || params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :username, :mail, :banned, :deleted)
  end
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { class: "form-horizontal user" } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row"><div class="col-md-6">
    <div class="control-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <%= error_span(@user[:name]) %>
    </div>
    <div class="control-group">
      <%= f.label :username, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :username, class: 'form-control' %>
      </div>
      <%= error_span(@user[:username]) %>
    </div>
    <div class="control-group">
      <%= f.label :mail, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :mail, class: 'form-control' %>
      </div>
      <%= error_span(@user[:mail]) %>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.check_box :banned %>
        <%= f.label :banned, class: 'control-label' %>
      </div>
      <%= error_span(@user[:banned]) %>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= f.check_box :deleted %>
        <%= f.label :deleted, class: 'control-label' %>
      </div>
      <%= error_span(@user[:deleted]) %>
    </div>
  </div></div>
  <div class="clearfix"></div>
  <br>

  <%= f.submit nil, class: 'btn btn-primary' %>
  <%= link_to t('cancel'), users_path, class: 'btn btn-default' %>

<% end %>

app/views/users/edit.html.erb
<div class="page-header">
  <h1><%=t 'users.edit_user' %></h1>
</div>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="page-header">
  <h1><%=t 'users.users' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= User.human_attribute_name(:id) %></th>
      <th><%= User.human_attribute_name(:name) %></th>
      <th><%= User.human_attribute_name(:username) %></th>
      <th><%= User.human_attribute_name(:mail) %></th>
      <th><%= User.human_attribute_name(:banned) %></th>
      <th><%= User.human_attribute_name(:deleted) %></th>
      <th><%=t 'actions' %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.mail %></td>
        <td><%= boolean_mark user.banned %></td>
        <td><%= boolean_mark user.deleted %></td>
        <td>
          <%= link_to t('edit'), edit_user_path(user), class: 'btn btn-default btn-xs' %>
          <%= link_to t('destroy'), user_path(user),
                      method: :delete,
                      data: { confirm: t('confirm') },
                      class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('users.new_user'), new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<div class="page-header">
  <h1><%=t 'users.new_user' %></h1>
</div>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <h1><%=t 'users.user' %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= User.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= User.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @user.username %></dd>
  <dt><strong><%= User.human_attribute_name(:mail) %>:</strong></dt>
  <dd><%= @user.mail %></dd>
  <dt><strong><%= User.human_attribute_name(:banned) %>:</strong></dt>
  <dd><%= boolean_mark @user.banned %></dd>
  <dt><strong><%= User.human_attribute_name(:deleted) %>:</strong></dt>
  <dd><%= boolean_mark @user.deleted %></dd>
</dl>

<h2><%=t 'users.roles' %>:</h2>
<ul>
  <% @roles.each do |role| %>
    <li>
      <%= role.name %>
      <% if policy(@user).destroy_role? %>
        <%= link_to t('remove'), user_destroy_role_path(@user, role), method: :delete,
                    class: ['btn', 'btn-danger', 'btn-xs'] %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if policy(@user).new_role? %>
  <%= form_for @user, url: user_new_role_path(@user), method: :post, html: {class: 'form-inline'} do |f| %>
    <div class="form-group">
      <%= select_tag 'user[role_id]', options_from_collection_for_select(Role.all, 'id', 'name'),
                     class: 'form-control' %>
      <%= f.submit t('users.add_role'), class: ['btn', 'btn-primary'] %>
    </div>
  <% end %>
<% end %>

<br>
  <%= link_to t('back'), users_path, class: 'btn btn-default'  %>
  <%= link_to t('edit'), edit_user_path(@user), class: 'btn btn-default' %>
  <%= link_to t('destroy'), user_path(@user),
                method: 'delete',
                data: { confirm: t('confirm') },
                class: 'btn btn-danger' %>