config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'home#index'

  get '/login', to: 'login#login', as: 'login'
  post '/login', to: 'login#do_login'
  delete '/logout', to: 'login#logout', as: 'logout'

  resources :roles
  resources :months
  resources :events
  resources :payments
  resources :notifications
  resources :users do
    delete '/:role_id', action: 'destroy_role', as: 'destroy_role'
    post '/new_role', action: 'new_role', as: 'new_role'
  end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  validates_presence_of :user_id, :month_id
  validates_uniqueness_of :user_id, scope: :month_id

  belongs_to :user
  belongs_to :month
  belongs_to :event
end

app/controllers/concerns/payment_helper.rb
class PaymentHelper
  def self.cost_per_person
    num_users = User.count(deleted: false)
    return 0 if num_users == 0

    cost_per_month = APP_CONFIG['cost_per_month']
    cost = (cost_per_month.to_f / num_users).round(1)

    [cost, 1.0].max
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :load_payment, only: [:show, :update, :edit, :destroy]

  def index
    authorize :payment, :index?

    @payments = Payment.all
    respond_to do |f|
      f.html
      f.json { render json: @payments }
    end
  end
  def show
    authorize @payment

    respond_to do |f|
      f.html
      f.json { render json: @payments }
    end
  end

  def update
    authorize @payment

    if @payment.update(payment_params)
      redirect_to @payment
    else
      render :edit
    end
  end
  def edit
    authorize @payment
    @users = User.all
    @months = Month.all
  end

  def create
    @payment = Payment.new(payment_params)
    authorize @payment

    date = Date.today
    date = @payment.month.firstDay if date < @payment.month.firstDay

    event = Event.new date: date, amount: PaymentHelper.cost_per_person,
                      description: "Payment of #{@payment.user.name} in #{@payment.month.name}"

    begin
      ActiveRecord::Base.transaction do
        event.save!
        @payment.event = event
        @payment.save!
      end

      redirect_to @payment
    rescue Exception => e
      logger.error e.message
      e.backtrace.each {|l| logger.error(l)}
      new
      render :new
      return
    end
  end
  def new
    @payment = Payment.new
    @users = User.all
    @months = Month.all

    authorize @payment
  end

  def destroy
    authorize @payment

    event = @payment.event
    if event.payments.count == 1
      event.destroy!
    end

    if @payment.destroy
      redirect_to root_path
    else
      redirect_to @payment
    end
  end

  private

  def load_payment
    @payment = Payment.includes(:user, :month, :event).find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:user_id, :month_id)
  end
end

app/views/payments/_form.html.erb
<%= form_for @payment, :html => { class: "form-horizontal payment" } do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @payment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row"><div class="col-md-6">
    <div class="control-group">
      <%= f.label :user, class: 'control-label' %>
      <div class="controls">
        <%= f.select :user_id, options_from_collection_for_select(@users, "id", "name"), {}, class: 'form-control' %>
      </div>
      <%= error_span(@payment[:user_id]) %>
    </div>
    <div class="control-group">
      <%= f.label :month, class: 'control-label' %>
      <div class="controls">
        <%= f.select :month_id, options_from_collection_for_select(@months.reverse, "id", "locale_name"), {}, class: 'form-control' %>
      </div>
      <%= error_span(@payment[:month_id]) %>
    </div>
  </div></div>
  <div class="clearfix"></div>
  <br>

  <%= f.submit nil, class: 'btn btn-primary' %>
  <%= link_to t('cancel'), payments_path, class: 'btn btn-default' %>

<% end %>

app/views/payments/edit.html.erb
<div class="page-header">
  <h1><%=t 'payments.edit_payment' %></h1>
</div>
<%= render 'form' %>

app/views/payments/index.html.erb
<div class="page-header">
  <h1><%=t 'payments.payments' %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= Payment.human_attribute_name(:id) %></th>
    <th><%= Payment.human_attribute_name(:payment) %></th>
    <th><%= Payment.human_attribute_name(:month) %></th>
    <th><%=t 'actions' %></th>
  </tr>
  </thead>
  <tbody>
  <% @payments.each do |payment| %>
    <tr>
      <td><%= link_to payment.id, payment_path(payment) %></td>
      <td><%= payment.user.name %></td>
      <td><%= payment.month.locale_name %></td>
      <td>
        <%= link_to t('edit'), edit_payment_path(payment), class: 'btn btn-default btn-xs' %>
        <%= link_to t('destroy'), payment_path(payment),
                    method: :delete,
                    data: { confirm: t('confirm') },
                    class: 'btn btn-xs btn-danger' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('payments.new_payment'), new_payment_path, class: 'btn btn-primary' %>

app/views/payments/new.html.erb
<div class="page-header">
  <h1><%=t 'payments.new_payment' %></h1>
</div>
<%= render 'form' %>

app/views/payments/show.html.erb
<div class="page-header">
  <h1><%=t 'payments.payment' %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= Payment.human_attribute_name(:user) %>:</strong></dt>
  <dd><%= @payment.user.name %></dd>
  <dt><strong><%= Payment.human_attribute_name(:month) %>:</strong></dt>
  <dd><%= @payment.month.name %></dd>
</dl>

<br>
<%= link_to t('back'), payments_path, class: 'btn btn-default'  %>
<%= link_to t('edit'), edit_payment_path(@payment), class: 'btn btn-default' %>
<%= link_to t('destroy'), payment_path(@payment),
            method: 'delete',
            data: { confirm: t('confirm') },
            class: 'btn btn-danger' %>