config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'home#index'

  get '/login', to: 'login#login', as: 'login'
  post '/login', to: 'login#do_login'
  delete '/logout', to: 'login#logout', as: 'logout'

  resources :roles
  resources :months
  resources :events
  resources :payments
  resources :notifications
  resources :users do
    delete '/:role_id', action: 'destroy_role', as: 'destroy_role'
    post '/new_role', action: 'new_role', as: 'new_role'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include HttpAcceptLanguage::AutoLocale

  protect_from_forgery with: :exception

  helper_method :current_user

  protected

  def current_user
    if @current_user.nil?
      @current_user = Credential.find(session[:user_id]) rescue false
    end
    @current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def true_mark
    check_box_tag nil, 1, true, disabled: true
  end
  def false_mark
    check_box_tag nil, 0, false, disabled: true
  end

  def boolean_mark(status)
    status ? true_mark : false_mark
  end

  def format_date(date)
    date.strftime("%d/%m/%Y")
  end

  def format_currency(amount)
    number_to_currency amount, unit: '€ '
  end
end

app/views/application/_admin_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('navbar.admin'), root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to t('navbar.add_payment'), new_payment_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><%=t 'navbar.lists' %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to t('navbar.user'), users_path %></li>
            <li><%= link_to t('navbar.role'), roles_path %></li>
            <li><%= link_to t('navbar.month'), months_path %></li>
            <li><%= link_to t('navbar.notification'), notifications_path %></li>
            <li><%= link_to t('navbar.payment'), payments_path %></li>
            <li><%= link_to t('navbar.event'), events_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><%=t 'navbar.add' %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to t('navbar.user'), new_user_path %></li>
            <li><%= link_to t('navbar.role'), new_role_path %></li>
            <li><%= link_to t('navbar.month'), new_month_path %></li>
            <li><%= link_to t('navbar.notification'), new_notification_path %></li>
            <li><%= link_to t('navbar.payment'), new_payment_path %></li>
            <li><%= link_to t('navbar.event'), new_event_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><p class="navbar-text"><%=raw t 'navbar.login', username: current_user.username %></p></li>
        <li><%= button_to t('navbar.logout'), logout_path, method: :delete, class: ['btn', 'btn-default', 'navbar-btn'] %></li>
      </ul>
    </div>
  </div>
</nav>